site_name: Learn Helm
site_url: https://www.patashale.in/learn-helm/
site_author: Patashale™
site_description: Learn everything about Helm here at Patashale™.
repo_url: https://github.com/patashale/learn-helm
repo_name: patashale/learn-helm
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary:  blue
      accent:  blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlav.com/patashale
      name: Patashale™ on GitLab
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#0F1689"

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Commands: commands.md
  - Charts: charts.md
  - Plugins: plugins.md
  - Internals: internals.md
  - Registry: registry.md
  - Best Practices: best-practices.md

copyright: Copyright &copy; 2024 <a href="https://www.github.com/patashale">Patashale™</a>
